# Generated by Django 5.0.7 on 2024-08-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
