# Generated by Django 5.0.7 on 2024-09-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
