# Generated by Django 5.1.1 on 2024-10-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
