# Generated by Django 5.0.7 on 2024-10-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='ABC@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(default='ABC', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(default='ABC', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
