# Generated by Django 5.1.1 on 2024-10-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_supplier_email_remove_supplier_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.plant'),
        ),
    ]
